(function (Blockly) {
  Blockly.Msg = Blockly.Msg || {};
  Object.assign(Blockly.Msg, {
    // SynthBlockly Stage - English
    
    // Toolbar Tooltips
    "BKY_TOOLBAR_SAVE_TOOLTIP": "Save Project (XML)",
    "BKY_TOOLBAR_SAVE_AS_TOOLTIP": "Save As",
    "BKY_TOOLBAR_CLOSE_TOOLTIP": "Close Workspace",
    "BKY_TOOLBAR_NEW_TOOLTIP": "New Project",
    "BKY_TOOLBAR_OPEN_TOOLTIP": "Open Project",

    // Category Keys
    "CAT_STRUCTURE": "Structure",
    "CAT_LOGIC": "Logic",
    "CAT_LOOPS": "Loops",
    "CAT_MATH": "Math",
    "CAT_TEXT": "Text",
    "CAT_LISTS": "Lists",
    "CAT_VARIABLES": "Variables",
    "CAT_FUNCTIONS": "Functions",
    "CAT_TOOLS": "Tools",
    "CAT_LIVE_SHOW": "Live Show",
    "CAT_SOUND_SOURCES": "Sound Sources",
    "CAT_INSTRUMENT_CONTROL": "Instrument Control",
    "CAT_PERFORMANCE": "Performance",
    "CAT_MIDI": "MIDI",
    "CAT_PC_KEY": "PC Keyboard",
    "CAT_SERIAL": "Serial",
    "CAT_VISUAL": "Visuals",
    "CAT_UI": "UI Control",

    // Effect Blocks
    "SB_SETUP_EFFECT_MESSAGE": "Set Effect Type %1",
    "SB_EFFECT_FILTER_TYPE_FIELD": "Filter",
    "SB_EFFECT_DELAY_TYPE_FIELD": "Delay",
    "SB_EFFECT_BITCRUSH_TYPE_FIELD": "BitCrush",
    "SB_EFFECT_WAVESHAPER_TYPE_FIELD": "Waveshaper",
    "SB_EFFECT_COMPRESSOR_TYPE_FIELD": "Compressor",
    "SB_EFFECT_LIMITER_TYPE_FIELD": "Limiter",
    "SB_EFFECT_REVERB_TYPE_FIELD": "Reverb",
    "SB_EFFECT_FLANGER_TYPE_FIELD": "Flanger",
    "SB_EFFECT_AUTOFILTER_TYPE_FIELD": "Auto-Filter",
    "SB_EFFECT_PITCHMOD_TYPE_FIELD": "Pitch-Mod",
    "SB_EFFECT_FILTER_INTERNAL_TYPE_FIELD": "Mode",
    "SB_EFFECT_MOD_TYPE_FIELD": "Modulation Type",
    "SB_EFFECT_MOD_TYPE_JITTER": "Jitter",
    "SB_EFFECT_MOD_TYPE_VIBRATO": "Vibrato",
    "SB_EFFECT_FILTER_FREQ_FIELD": "Frequency",
    "SB_EFFECT_FILTER_Q_FIELD": "Resonance (Q)",
    "SB_EFFECT_DELAY_TIME_FIELD": "Delay Time (s)",
    "SB_EFFECT_FEEDBACK_FIELD": "Feedback",
    "SB_EFFECT_RATE_FIELD": "Rate (Hz)",
    "SB_EFFECT_DEPTH_FIELD": "Depth",
    "SB_EFFECT_BITDEPTH_FIELD": "Bit Depth (Bits)",
    "SB_EFFECT_DISTORTION_AMOUNT_FIELD": "Distortion Amount",
    "SB_EFFECT_ROOMSIZE_FIELD": "Room Size",
    "SB_EFFECT_DAMPING_FIELD": "Damping",
    "SB_EFFECT_WET_FIELD": "Wet Level",
    "SB_EFFECT_ROLLOFF_FIELD": "Rolloff",
    "SB_EFFECT_THRESHOLD_FIELD": "Threshold (dB)",
    "SB_EFFECT_RATIO_FIELD": "Ratio",
    "SB_EFFECT_ATTACK_FIELD": "Attack (s)",
    "SB_EFFECT_RELEASE_FIELD": "Release (s)",
    "SB_EFFECT_MAKEUP_FIELD": "Makeup Gain (dB)",
    "SB_SETUP_EFFECT_TOOLTIP": "Setup and apply an audio effect. Place inside an instrument container for instrument-specific effects, or outside (e.g., in setup) for global Master effects. Supports serial chaining of multiple effects.",
    "SB_SET_EFFECT_PARAM_TITLE": "Update effect param for %1 type %2",
    "SB_SET_EFFECT_PARAM_PARAM": "param %1",
    "SB_SET_EFFECT_PARAM_VALUE": "value",
    "SB_SET_EFFECT_PARAM_PAN_LABEL": "position (-1~1)",
    "SB_UPDATE_ADSR_TITLE": "Update ADSR for %1",
    "SB_SET_EFFECT_PARAM_TOOLTIP": "Update an instrument's effect parameters in real-time.",
    "SB_UPDATE_ADSR_TOOLTIP": "Update an instrument's ADSR envelope in real-time.",
    "SB_SELECT_INSTRUMENT_PROMPT": "(Select Instrument)",
    "SB_CURRENT_INSTRUMENT_OPTION": "Current Selected Instrument",
    "SB_NO_EFFECTS_AVAILABLE": "(No effects available)",
    "SB_NO_INSTRUMENT_SELECTED": "(No instrument selected)",
    "SB_ERROR_INSTRUMENT_NOT_FOUND": "Instrument container not found: %1",
    "SB_ERROR_EFFECT_NOT_FOUND": "Effect not found in instrument's current setup: %1",

    // Live Show Blocks
    "LIVE_SET_PARAM": "Set stage param %1 to %2",
    "LIVE_GET_PARAM": "Stage param %1",
    "SB_LOG_TO_SCREEN": "Write to Stage Log %1 Type %2",
    "SB_LOG_TYPE_INFO": "INFO",
    "SB_LOG_TYPE_MSG": "!",
    "SB_LOG_TYPE_WARN": "WARN",
    "SB_LOG_TYPE_ERR": "ERR",
    "SB_LOG_TO_SCREEN_TOOLTIP": "Output a message to the stage's console or alerts area.",
    "LIVE_PARAM_WAVE_SCALE": "Wave Scale",
    "LIVE_PARAM_TRAIL_ALPHA": "Trail Alpha",
    "LIVE_PARAM_FG_HUE": "FG Color Hue",
    "LIVE_PARAM_MASTER_GAIN": "Master Gain",
    "LIVE_PARAM_TRANSPOSE": "Transpose",
    "LIVE_PARAM_ADSR_A": "Envelope A",
    "LIVE_PARAM_ADSR_D": "Envelope D",
    "LIVE_PARAM_ADSR_S": "Envelope S",
    "LIVE_PARAM_ADSR_R": "Envelope R",

    // Serial Blocks
    "SERIAL_INIT": "Init Serial Port Index %1 Baud %2",
    "SERIAL_AVAILABLE": "Serial Data Available?",
    "SERIAL_READ_STRING": "Read String until Newline",
    "SERIAL_WRITE": "Write Serial %1",
    "SERIAL_DATA_RECEIVED": "When Serial data received %1 store in %2 %3",
    "SERIAL_CHECK_MASK": "Check Mask %1 for Key %2",
    "SB_SERIAL_CHECK_KEY_MASK_MESSAGE": "Is Key %2 Pressed in Data %1?",
    "SB_SERIAL_CHECK_KEY_MASK_TOOLTIP": "Parses bitmask data (e.g., KEYS:5) to check if a specific key is pressed.",

    // Tools Blocks
    "TOOLS_COMMENT": "Comment %1",

    // Visual Blocks
    "VISUAL_STAGE_SETUP_TITLE": "Setup Stage",
    "VISUAL_STAGE_SETUP_DIMENSIONS": "Dimensions: Width %1 Height %2",
    "VISUAL_STAGE_SETUP_APPEARANCE": "Appearance: BG %1   FG %2",
    "VISUAL_STAGE_SETUP_SETTINGS": "Options: Wave %1   |   Spec %2   |   Log %3   |   MIDI %4",
    "VISUAL_STAGE_SET_COLOR": "Set stage %1 color to %2",
    "VISUAL_ELLIPSE": "Draw Ellipse x %1 y %2 w %3 h %4",
    "VISUAL_TRIANGLE": "Draw Triangle x1 %1 y1 %2 x2 %3 y2 %4 x3 %5 y3 %6",
    "VISUAL_ROTATE": "Rotate %1 deg",
    "VISUAL_TRANSLATE": "Translate x %1 y %2",
    "VISUAL_PUSH_POP": "Isolate Transforms %1",
    "VISUAL_SCALE": "Scale %1x",
    "AUDIO_CREATE_SYNTH_INSTRUMENT": "Create Synth Instrument Name %1 Type %2",
    "AUDIO_CREATE_HARMONIC_SYNTH": "Set as Harmonic Synth",
    "AUDIO_CREATE_ADDITIVE_SYNTH": "Set as Additive Synth",
    "SB_INSTRUMENT_CONTAINER_MESSAGE": "Define Instrument Name %1 %2",
    "SB_INSTRUMENT_CONTAINER_TOOLTIP": "Instrument definition container. Place waveform and ADSR settings inside.",
    "SB_INSTRUMENT_CONTAINER_MULTI_SOURCE_WARN": "Warning: An instrument container can only have one sound source block (Waveform, Noise, Sampler, or Synth). Subsequent blocks will overwrite the previous type.",
    "SB_SET_ADSR_MESSAGE": "Set ADSR",
    "SB_SET_ADSR_TOOLTIP": "Set the ADSR envelope for this instrument (0.0 ~ 1.0+).",
    "SB_SET_WAVE_MESSAGE": "Set Waveform",
    "SB_SET_WAVE_TOOLTIP": "Set the basic waveform for this instrument.",
    "SB_SET_NOISE_MESSAGE": "Set Noise Type %1",
    "SB_SET_NOISE_TOOLTIP": "Set this instrument as a noise generator (useful for percussion effects or atmosphere).",
    "SB_MIXED_SOURCE_MESSAGE": "Set Mixed Source Wave %1 + Noise %2 Mix(Noise %) %3",
    "SB_MIXED_SOURCE_TOOLTIP": "Mix basic waveform and random noise to create complex tones with texture or airiness.",
    "SB_MIXED_SOURCE_JITTER": "Jitter",
    "SB_MIXED_SOURCE_SWEEP_RATE": "Sweep Rate",
    "SB_MIXED_SOURCE_SWEEP_DEPTH": "Sweep Depth",
    "SB_SET_PANNING_MESSAGE": "Set Panning",
    "SB_SET_PANNING_INST": "Instrument",
    "SB_SET_PANNING_VAL": "Position (-1~1)",
    "SB_SET_PANNING_TOOLTIP": "Adjust the position of the instrument in the stereo field. -1 is Left, 1 is Right, 0 is Center.",
    "AUDIO_HARMONIC_FIELD": "%1x Harmonic Amplitude (0-1)",
    "AUDIO_ADDITIVE_FIELD": "Wave %1 Freq Ratio %2 Amp %3",
    "AUDIO_CREATE_MELODIC_SAMPLER": "Set Sampler (Melodic) Source %1",
    "AUDIO_CREATE_DRUM_SAMPLER": "Set Sampler (Drum) Source %1",
    "AUDIO_SAMPLER_CUSTOM": "Custom Path...",
    "AUDIO_SAMPLER_PATH_FIELD": "Path",
    "AUDIO_MELODIC_SAMPLER_PIANO": "Piano",
    "AUDIO_MELODIC_SAMPLER_VIOLIN_PIZZ": "Violin (Pizzicato)",
    "AUDIO_MELODIC_SAMPLER_VIOLIN_ARCO": "Violin (Arco)",
    "AUDIO_MELODIC_SAMPLER_CUSTOM": "Custom Folder...",
    "AUDIO_MELODIC_SAMPLER_TOOLTIP": "Creates a pitch-shifting sampler instrument. Automatically loads samples from a folder and performs smart pitch shifting.",
    "AUDIO_DRUM_SAMPLER_TOOLTIP": "Load a percussive sound sample (WAV/MP3/AIFF).",
    "AUDIO_SELECT_INSTRUMENT": "Select Instrument %1",
    "AUDIO_SELECT_INSTRUMENT_TOOLTIP": "Select an instrument from the list of defined instruments in the workspace to be the active one for performance.",
    "AUDIO_SET_INSTRUMENT_VOLUME": "Set Volume",
    "AUDIO_SET_INSTRUMENT_VOLUME_INST": "Instrument",
    "AUDIO_SET_INSTRUMENT_VOLUME_VAL": "Level %",
    "AUDIO_SET_INSTRUMENT_VOLUME_TOOLTIP": "Adjust the volume level of a specific instrument (0-100).",
    "AUDIO_SELECT_INSTRUMENT_DROPDOWN": "(Select Inst)",
    "AUDIO_SELECT_CHORD_DROPDOWN": "(Select Chord)",
    "AUDIO_TRIGGER_SAMPLE": "Play Single Note",
    "AUDIO_TRIGGER_SAMPLE_INST": "Instrument",
    "AUDIO_TRIGGER_SAMPLE_NOTE": "Note",
    "AUDIO_TRIGGER_SAMPLE_VEL": "Velocity",
    "AUDIO_TRIGGER_SAMPLE_TOOLTIP": "Play a single note or hit. Examples: 'C4' (default quarter), 'X' (hit), 'C4H' (half note). Suffixes: W(Whole), H(Half), Q(Quarter), E(Eighth), S(Sixteenth).",
    "HELP_LANG_SUFFIX": "_en.html",
    "HELP_HINT": "\nRight-click and select 'Help' for more details.",
    "AUDIO_PLAY_NOTE": "Play Sustained Note",
    "AUDIO_PLAY_NOTE_INST": "Inst",
    "AUDIO_PLAY_NOTE_PITCH": "Pitch",
    "AUDIO_PLAY_NOTE_VEL": "Velocity",
    "AUDIO_STOP_NOTE": "Stop Sustained Note",
    "AUDIO_STOP_NOTE_INST": "Inst",
    "AUDIO_STOP_NOTE_PITCH": "Pitch",
    "AUDIO_PLAY_NOTE_TOOLTIP": "Start playing a sustained note with the specified instrument. Pitch supports MIDI number (e.g., 60) or note name (e.g., 'C4'). Usually used with keyboard or MIDI Note On events.",
    "AUDIO_STOP_NOTE_TOOLTIP": "Stop playing a specific pitch with the specified instrument. Pitch supports MIDI number (e.g., 60) or note name (e.g., 'C4'). Usually used with keyboard or MIDI Note Off events.",
    "AUDIO_PLAY_MELODY": "Play Melody",
    "AUDIO_PLAY_MELODY_INST": "Instrument",
    "AUDIO_PLAY_MELODY_SCORE": "Score",
    "AUDIO_PLAY_MELODY_TOOLTIP": "Play according to the list. Supports multi-line, notes (C4, D4) and chords (CM7, G7).",
    "AUDIO_TONE_LOOP": "Loop Playback Every %1 %2",
    "AUDIO_RHYTHM_SEQUENCE": "Step Sequencer",
    "AUDIO_RHYTHM_SEQUENCE_INST": "Inst",
    "AUDIO_RHYTHM_SEQUENCE_MODE": "Mode",
    "AUDIO_RHYTHM_SEQUENCE_MEASURE": "Measure",
    "AUDIO_RHYTHM_SEQUENCE_PATTERN": "Pattern",
    "AUDIO_RHYTHM_SEQUENCE_VELOCITY": "Velocity",
    "AUDIO_RHYTHM_V2_HEADER": "Arrange Phrase M. %1 | TS %2/%3 | Resolution %4",
    "AUDIO_RHYTHM_V2_TRACK": "Inst %1 Vel %2 Mode %3 Pattern %4",
    "AUDIO_RHYTHM_MODE_MONO": "Mono/Percussion",
    "AUDIO_RHYTHM_MODE_CHORD": "Chord",
    "AUDIO_RHYTHM_SEQUENCE_TOOLTIP": "Plays rhythm steps in a specific measure. Supports 'x' (trigger) or notes/chords.",
    "AUDIO_COUNT_IN": "Count-in %1 measures TS %2 / %3 Velocity %4",
    "AUDIO_SET_BPM": "Set Tempo (BPM) %1",
    "AUDIO_DEFINE_CHORD": "Define Chord Name %1 Notes %2",
    "AUDIO_PLAY_CHORD_BY_NAME": "Play Chord",
    "AUDIO_PLAY_CHORD_BY_NAME_INST": "Instrument",
    "AUDIO_PLAY_CHORD_BY_NAME_DUR": "Duration",
    "AUDIO_PLAY_CHORD_BY_NAME_VEL": "Velocity",
    "SB_PLAY_DRUM_MESSAGE": "Play Electronic Drum %1 Velocity %2",
    "SB_PLAY_DRUM_TOOLTIP": "Play electronic drum samples (Kick/Snare/HiHat/Clap).",
    "MIDI_ON_NOTE": "When %1 MIDI Note ON %2 Channel %3 Pitch %4 Vel %5 %6 %7",
    "MIDI_OFF_NOTE": "When %1 MIDI Note OFF %2 Channel %3 Pitch %4 Vel %5 %6 %7",
    "MIDI_ON_CONTROLLER_CHANGE": "When %1 MIDI CC Signal %2 Channel %3 Num %4 Val %5 %6 %7",
    "MIDI_ON_CONTROLLER_CHANGE_TOOLTIP": "Listen for MIDI Control Change (CC) signals.",
    "MIDI_INIT": "Init MIDI %1 Input %2 Output %3",
    "MIDI_INIT_TOOLTIP": "Initialize MidiBus library. Check console for available device indices.",
    "MIDI_SEND_NOTE": "Send MIDI Note %1 Channel %2 Pitch %3 Velocity %4",
    "MIDI_SEND_NOTE_TOOLTIP": "Send a Note On or Note Off signal to the MIDI output device.",
    "MIDI_SEND_CC": "Send MIDI CC Channel %1 Number %2 Value %3",
    "MIDI_SEND_CC_TOOLTIP": "Send a Control Change (CC) signal to the MIDI output device.",
    "MIDI_TYPE_ON": "ON",
    "MIDI_TYPE_OFF": "OFF",
    "MIDI_LP_XY_TO_NOTE": "Launchpad XY to Note x %1 y %2",
    "MIDI_LP_XY_TO_NOTE_TOOLTIP": "Convert Launchpad S X-Y coordinates (0-7) to corresponding MIDI note number. (0,0) is top-left.",
    "UI_KEY_EVENT": "When keyboard %1 key is %2",
    "UI_KEY_PRESSED": "pressed",
    "UI_KEY_RELEASED": "released",
    "UI_KEY_EVENT_TOOLTIP": "Action to perform when a specific key is pressed or released. Piano keys are reserved.",
    "UI_INIT": "Init UI System (ControlP5)",
    "UI_INIT_TOOLTIP": "Initialize ControlP5 library to create sliders and toggles.",
    "UI_ADD_SLIDER": "Add Slider %1 at x %2 y %3 size %4x%5 %6 range %7 to %8 init %9 label %10",
    "UI_ADD_TOGGLE": "Add Toggle Name %1 at x %2 y %3 init %4 label %5",
    "UI_SET_FONT_SIZE": "Set UI Font Size %1",
    "VISUAL_NO_STROKE": "No Stroke",
    "VISUAL_NO_FILL": "No Fill",
    "VISUAL_PIXEL_DENSITY": "Optimize High-Res Display (pixelDensity)",
    "VISUAL_PIXEL_DENSITY_TOOLTIP": "Enable 2x rendering on high-resolution displays (like Retina) for smoother lines.",
    "VISUAL_FRAME_RATE": "Set Frame Rate %1",
    "VISUAL_FRAME_RATE_TOOLTIP": "Set the number of times draw() is called per second. Default is 60.",
    "VISUAL_STAGE_SETUP_TOOLTIP": "Initialize the Super Stage (includes auto waveform and FFT).",
    "MIDI_ON_NOTE_TOOLTIP": "Action to perform when an external MIDI device note is pressed.",
    "MIDI_OFF_NOTE_TOOLTIP": "Action to perform when an external MIDI device note is released.",
    "AUDIO_TONE_LOOP_TOOLTIP": "Continuously loop the inner blocks. INTERVAL supports 1m, 2n, 4n etc.",
    "AUDIO_PERFORM_ONCE": "Perform %1",
    "AUDIO_PERFORM_ONCE_TOOLTIP": "Execute the inner performance blocks once in a background thread. Multiple Perform blocks can run simultaneously for polyphony.",
    "AUDIO_CREATE_HARMONIC_SYNTH_TOOLTIP": "Set this instrument as a Harmonic Synth.",
    "AUDIO_CREATE_ADDITIVE_SYNTH_TOOLTIP": "Set this instrument as an Additive Synth.",
    "VISUAL_STAGE_BG": "Background",
    "VISUAL_STAGE_WAVE": "Waveform",

    // Processing Structure Blocks
    "BKY_PROCESSING_SETUP_MSG_ANGEL": "When program starts (setup)",
    "BKY_PROCESSING_DRAW_MSG_ANGEL": "Repeat (draw)",
    "STRUCTURE_FRAME_COUNT": "Frame Count (frameCount)",
    "STRUCTURE_FRAME_COUNT_TOOLTIP": "Get the total number of frames passed since the program started.",
    
    "PROCESSING_SETUP_TOOLTIP": "setup() runs once when the program starts.",
    "PROCESSING_DRAW_TOOLTIP": "draw() runs repeatedly to update visuals and audio.",

    // Hues
    "STRUCTURE_HUE": "#16A085",
    "LOGIC_HUE": "#b198de",
    "LOOPS_HUE": "#7fcd81",
    "MATH_HUE": "#5C68A6",
    "LISTS_HUE": "#745ca6",
    "TEXT_HUE": "#6a8871",
    "VARIABLES_HUE": "#ef9a9a",
    "FUNCTIONS_HUE": "#d22f73",
    "TOOLS_HUE": "#6a8871",
    "LIVE_SHOW_HUE": "#2C3E50",
    "SOUND_SOURCES_HUE": "#AC4B40",
    "INSTRUMENT_CONTROL_HUE": "#FF5722",
    "EFFECTS_HUE": "#8E44AD",
    "PERFORMANCE_HUE": "#E67E22",
    "MIDI_HUE": "#5B67E7",
    "PC_KEY_HUE": "#2c3e50",
    "SERIAL_HUE": "#2c3e50",
    "UI_HUE": "#FFB300",
    "VISUAL_HUE": "#3498DB",

    "VISUAL_EXIT": "Exit Program",
    "VISUAL_EXIT_TOOLTIP": "Immediately close the stage and end the program.",
    "SB_WAIT_MUSICAL": "Wait %1 %2",
    "SB_WAIT_UNIT_MS": "ms",
    "SB_WAIT_UNIT_S": "seconds",
    "SB_WAIT_UNIT_BEATS": "beats",
    "SB_WAIT_UNIT_MEASURES": "measures",
    "SB_WAIT_UNIT_MICROS": "µs",
    "SB_WAIT_MUSICAL_TOOLTIP": "Pause execution for a specific duration. You can choose musical units (beats, measures) or time units (seconds, ms).",
    "SB_MUSICAL_SECTION": "Arrange Phrase length %1 measures %2 %3",
    "SB_MUSICAL_SECTION_TOOLTIP": "A container to arrange a musical phrase. It starts all inner performances simultaneously and waits for the specified number of measures before proceeding.",
    "AUDIO_IS_PLAYING": "Is any melody playing?",
    "AUDIO_IS_PLAYING_TOOLTIP": "Check if the background melody player is still active.",
    "BKY_CONTROLS_DO": "do",
  });
})(Blockly);