(function (Blockly) {
  Blockly.Msg = Blockly.Msg || {};
  Object.assign(Blockly.Msg, {
    // SynthBlockly Stage - English
    
    // Toolbar Tooltips
    "BKY_TOOLBAR_SAVE_TOOLTIP": "Save Project (XML)",
    "BKY_TOOLBAR_SAVE_AS_TOOLTIP": "Save As",
    "BKY_TOOLBAR_CLOSE_TOOLTIP": "Close Workspace",
    "BKY_TOOLBAR_NEW_TOOLTIP": "New Project",
    "BKY_TOOLBAR_OPEN_TOOLTIP": "Open Project",

    // Category Keys
    "CAT_STRUCTURE": "Structure",
    "CAT_LOGIC": "Logic",
    "CAT_LOOPS": "Loops",
    "CAT_MATH": "Math",
    "CAT_TEXT": "Text",
    "CAT_LISTS": "Lists",
    "CAT_VARIABLES": "Variables",
    "CAT_FUNCTIONS": "Functions",
    "CAT_TOOLS": "Tools",
    "CAT_LIVE_SHOW": "Live Show",
    "CAT_SOUND_SOURCES": "Sound Sources",
    "CAT_INSTRUMENT_CONTROL": "Instrument Control",
    "CAT_PERFORMANCE": "Performance",
    "CAT_MIDI": "MIDI",
    "CAT_PC_KEY": "PC Keyboard",
    "CAT_SERIAL": "Serial",
    "CAT_VISUAL": "Visuals",
    "CAT_UI": "UI Control",

    // Live Show Blocks
    "LIVE_SET_PARAM": "Set stage param %1 to %2",
    "LIVE_GET_PARAM": "Stage param %1",
    "LIVE_PARAM_WAVE_SCALE": "Wave Scale",
    "LIVE_PARAM_TRAIL_ALPHA": "Trail Alpha",
    "LIVE_PARAM_FG_HUE": "FG Color Hue",
    "LIVE_PARAM_MASTER_GAIN": "Master Gain",
    "LIVE_PARAM_TRANSPOSE": "Transpose",
    "LIVE_PARAM_ADSR_A": "Envelope A",
    "LIVE_PARAM_ADSR_D": "Envelope D",
    "LIVE_PARAM_ADSR_S": "Envelope S",
    "LIVE_PARAM_ADSR_R": "Envelope R",

    // Serial Blocks
    "SERIAL_INIT": "Init Serial Port Index %1 Baud %2",
    "SERIAL_AVAILABLE": "Serial Data Available?",
    "SERIAL_READ_STRING": "Read String until Newline",
    "SERIAL_DATA_RECEIVED": "When Serial data received %1 store in %2 %3",
    "SERIAL_CHECK_MASK": "Check Mask %1 for Key %2",

    // Tools Blocks
    "TOOLS_COMMENT": "Comment %1",

    // Visual Blocks
    "VISUAL_STAGE_SETUP_TITLE": "Setup Stage",
    "VISUAL_STAGE_SETUP_DIMENSIONS": "Dimensions: Width %1 Height %2",
    "VISUAL_STAGE_SETUP_APPEARANCE": "Appearance: BG %1   FG %2",
    "VISUAL_STAGE_SETUP_SETTINGS": "Options: Wave %1   |   Spec %2   |   Log %3   |   MIDI %4",
    "VISUAL_STAGE_SET_COLOR": "Set stage %1 color to %2",
    "AUDIO_CREATE_SYNTH_INSTRUMENT": "Create Synth Instrument Name %1 Type %2",
    "AUDIO_CREATE_HARMONIC_SYNTH": "Set as Harmonic Synth",
    "AUDIO_CREATE_ADDITIVE_SYNTH": "Set as Additive Synth",
    "SB_INSTRUMENT_CONTAINER_MESSAGE": "Define Instrument Name %1 %2",
    "SB_INSTRUMENT_CONTAINER_TOOLTIP": "Instrument definition container. Place waveform and ADSR settings inside.",
    "SB_SET_ADSR_MESSAGE": "Set ADSR",
    "SB_SET_ADSR_TOOLTIP": "Set the ADSR envelope for this instrument (0.0 ~ 1.0+).",
    "SB_SET_WAVE_MESSAGE": "Set Waveform",
    "SB_SET_WAVE_TOOLTIP": "Set the basic waveform for this instrument.",
    "AUDIO_HARMONIC_FIELD": "%1x Harmonic Amplitude (0-1)",
    "AUDIO_ADDITIVE_FIELD": "Wave %1 Freq Ratio %2 Amp %3",
    "AUDIO_SELECT_INSTRUMENT": "Select Instrument %1",
    "AUDIO_SELECT_INSTRUMENT_TOOLTIP": "Select an instrument from the list of defined instruments in the workspace to be the active one for performance.",
    "AUDIO_SELECT_INSTRUMENT_DROPDOWN": "(Select Inst)",
    "AUDIO_SELECT_CHORD_DROPDOWN": "(Select Chord)",
    "AUDIO_TRIGGER_SAMPLE": "Play Single Note %1 Note %2 Velocity %3",
    "AUDIO_TRIGGER_SAMPLE_TOOLTIP": "Play a note or sample. Supports pitch + duration (e.g. C4Q, RE). Samples ignore pitch; use XQ or C4Q as a trigger.",
    "HELP_LANG_SUFFIX": "_en.html",
    "HELP_HINT": "\nRight-click and select 'Help' for more details.",
    "AUDIO_PLAY_NOTE": "Synth Start Pitch %1 Velocity %2",
    "AUDIO_STOP_NOTE": "Synth Stop (MIDI %1)",
    "AUDIO_PLAY_MELODY": "Play Melody with Instrument %1 %2 Score %3",
    "AUDIO_PLAY_MELODY_TOOLTIP": "Play according to the list. Supports multi-line, notes (C4, D4) and chords (CM7, G7).",
    "AUDIO_RHYTHM_SEQUENCE": "Step Sequencer %1 Inst %2 Vel %6 Mode %3 Measure %4 Pattern %5",
    "AUDIO_COUNT_IN": "Count-in %1 measures Vel %2",
    "AUDIO_SET_BPM": "Set Tempo (BPM) %1",
    "AUDIO_DEFINE_CHORD": "Define Chord Name %1 Notes %2",
    "AUDIO_PLAY_CHORD_BY_NAME": "Play Chord %1 Dur %2 Velocity %3",
    "MIDI_OFF_NOTE": "When MIDI Note OFF %1 %2 Channel %3 Pitch %4 Velocity %5 %6 %7",
    "UI_KEY_EVENT": "When keyboard %1 key pressed %2",
    "UI_KEY_EVENT_TOOLTIP": "Action to perform when a specific key is pressed. Piano keys are reserved.",
    "UI_INIT": "Init UI System (ControlP5)",
    "UI_INIT_TOOLTIP": "Initialize ControlP5 library to create sliders and toggles.",
    "UI_ADD_SLIDER": "Add Slider %1 at x %2 y %3 size %4 x %5 %6 range %7 to %8 init %9 label %10",
    "UI_ADD_TOGGLE": "Add Toggle Name %1 at x %2 y %3 init %4 label %5",
    "UI_SET_FONT_SIZE": "Set UI Font Size %1",
    "VISUAL_NO_STROKE": "No Stroke",
    "VISUAL_NO_FILL": "No Fill",
    "VISUAL_PIXEL_DENSITY": "Optimize High-Res Display (pixelDensity)",
    "VISUAL_PIXEL_DENSITY_TOOLTIP": "Enable 2x rendering on high-resolution displays (like Retina) for smoother lines.",
    "VISUAL_FRAME_RATE": "Set Frame Rate %1",
    "VISUAL_FRAME_RATE_TOOLTIP": "Set the number of times draw() is called per second. Default is 60.",
    "VISUAL_STAGE_SETUP_TOOLTIP": "Initialize the Super Stage (includes auto waveform and FFT).",
    "MIDI_ON_NOTE_TOOLTIP": "Action to perform when an external MIDI device note is pressed.",
    "MIDI_OFF_NOTE_TOOLTIP": "Action to perform when an external MIDI device note is released.",
    "AUDIO_TONE_LOOP": "Loop Playback Every %1 %2",
    "AUDIO_TONE_LOOP_TOOLTIP": "Continuously loop the inner blocks. INTERVAL supports 1m, 2n, 4n etc.",
    "AUDIO_PERFORM_ONCE": "Perform %1",
    "AUDIO_PERFORM_ONCE_TOOLTIP": "Execute the inner performance blocks once in a background thread. Multiple Perform blocks can run simultaneously for polyphony.",
    "AUDIO_CREATE_HARMONIC_SYNTH_TOOLTIP": "Set this instrument as a Harmonic Synth.",
    "AUDIO_CREATE_ADDITIVE_SYNTH_TOOLTIP": "Set this instrument as an Additive Synth.",
    "VISUAL_STAGE_BG": "Background",
    "VISUAL_STAGE_WAVE": "Waveform",

    // Processing Structure Blocks
    "BKY_PROCESSING_SETUP_MSG_ANGEL": "When program starts (setup)",
    "BKY_PROCESSING_DRAW_MSG_ANGEL": "Repeat (draw)",
    "STRUCTURE_FRAME_COUNT": "Frame Count (frameCount)",
    "STRUCTURE_FRAME_COUNT_TOOLTIP": "Get the total number of frames passed since the program started.",
    
    "PROCESSING_SETUP_TOOLTIP": "setup() runs once when the program starts.",
    "PROCESSING_DRAW_TOOLTIP": "draw() runs repeatedly to update visuals and audio.",

    // Hues
    "STRUCTURE_HUE": "#16A085",
    "LOGIC_HUE": "#b198de",
    "LOOPS_HUE": "#7fcd81",
    "MATH_HUE": "#5C68A6",
    "LISTS_HUE": "#745ca6",
    "TEXT_HUE": "#6a8871",
    "VARIABLES_HUE": "#ef9a9a",
    "FUNCTIONS_HUE": "#d22f73",
    "TOOLS_HUE": "#6a8871",
    "LIVE_SHOW_HUE": "#2C3E50",
    "SOUND_SOURCES_HUE": "#E74C3C",
    "INSTRUMENT_CONTROL_HUE": "#D22F73",
    "PERFORMANCE_HUE": "#E67E22",
    "MIDI_HUE": "#5B67E7",
    "PC_KEY_HUE": "#2c3e50",
    "SERIAL_HUE": "#2c3e50",
    "UI_HUE": "#FFB300",
    "VISUAL_HUE": "#3498DB",

    "VISUAL_EXIT": "Exit Program",
    "VISUAL_EXIT_TOOLTIP": "Immediately close the stage and end the program.",
    "STRUCTURE_DELAY": "Wait %1 ms",
    "STRUCTURE_DELAY_TOOLTIP": "Pause program execution for a period of time. Note: This will also pause visual animations.",
    "AUDIO_IS_PLAYING": "Is any melody playing?",
    "AUDIO_IS_PLAYING_TOOLTIP": "Check if the background melody player is still active.",
    "BKY_CONTROLS_DO": "do",
  });
})(Blockly);