(function (Blockly) {
  Blockly.Msg = Blockly.Msg || {};
  Object.assign(Blockly.Msg, {
    // SynthBlockly Stage - Traditional Chinese
    
    // Toolbar Tooltips
    "BKY_TOOLBAR_SAVE_TOOLTIP": "儲存專案 (XML)",
    "BKY_TOOLBAR_SAVE_AS_TOOLTIP": "另存專案",
    "BKY_TOOLBAR_CLOSE_TOOLTIP": "關閉工作區",
    "BKY_TOOLBAR_NEW_TOOLTIP": "建立新專案",
    "BKY_TOOLBAR_OPEN_TOOLTIP": "開啟專案",

    // Category Keys
    "CAT_STRUCTURE": "程式結構",
    "CAT_LOGIC": "邏輯判斷",
    "CAT_LOOPS": "迴圈控制",
    "CAT_MATH": "數學運算",
    "CAT_TEXT": "文字處理",
    "CAT_LISTS": "列表處理",
    "CAT_VARIABLES": "變數管理",
    "CAT_FUNCTIONS": "自訂函式",
    "CAT_TOOLS": "工具",
    "CAT_LIVE_SHOW": "即時表演",
    "CAT_SOUND_SOURCES": "音源建立",
    "CAT_INSTRUMENT_CONTROL": "樂器控制",
    "CAT_PERFORMANCE": "音樂演奏",
    "CAT_MIDI": "MIDI 通訊",
    "CAT_PC_KEY": "電腦鍵盤 (PC Key)",
    "CAT_SERIAL": "序列埠通訊 (Serial)",
    "CAT_EFFECTS": "音訊效果器",
    "CAT_UI": "介面控制 (UI)",
    "CAT_VISUAL": "視覺繪圖",

    // Effect Blocks
    "SB_SETUP_EFFECT_MESSAGE": "設定效果器 類型 %1",
    "SB_EFFECT_FILTER_TYPE_FIELD": "濾波器 (Filter)",
    "SB_EFFECT_DELAY_TYPE_FIELD": "延遲 (Delay)",
    "SB_EFFECT_BITCRUSH_TYPE_FIELD": "位元破壞 (BitCrush)",
    "SB_EFFECT_FILTER_INTERNAL_TYPE_FIELD": "模式",
    "SB_EFFECT_FILTER_FREQ_FIELD": "頻率",
    "SB_EFFECT_FILTER_Q_FIELD": "共振 (Q)",
    "SB_EFFECT_DELAY_TIME_FIELD": "延遲時間 (秒)",
    "SB_EFFECT_FEEDBACK_FIELD": "回饋 (Feedback)",
    "SB_EFFECT_BITDEPTH_FIELD": "位元深度 (Bits)",

    // Tools Blocks
    "LIVE_SET_PARAM": "設定舞台參數 %1 為 %2",
    "LIVE_GET_PARAM": "舞台參數 %1",
    "LIVE_PARAM_WAVE_SCALE": "波形縮放 (waveScale)",
    "LIVE_PARAM_TRAIL_ALPHA": "殘影透明度 (trailAlpha)",
    "LIVE_PARAM_FG_HUE": "前景顏色 (fgHue)",
    "LIVE_PARAM_MASTER_GAIN": "主音量 (masterGain)",
    "LIVE_PARAM_TRANSPOSE": "移調 (pitchTranspose)",
    "LIVE_PARAM_ADSR_A": "包絡線 A (adsrA)",
    "LIVE_PARAM_ADSR_D": "包絡線 D (adsrD)",
    "LIVE_PARAM_ADSR_S": "包絡線 S (adsrS)",
    "LIVE_PARAM_ADSR_R": "包絡線 R (adsrR)",

    // Serial Blocks
    "SERIAL_INIT": "初始化序列埠 索引 %1 波特率 %2",
    "SERIAL_AVAILABLE": "序列埠有新資料？",
    "SERIAL_READ_STRING": "讀取字串直到換行",
    "SERIAL_WRITE": "寫入序列埠 內容 %1",
    "SERIAL_DATA_RECEIVED": "當收到序列埠資料時 %1 存入變數 %2 %3",
    "SERIAL_CHECK_MASK": "檢查位元遮罩 %1 是否包含鍵碼 %2",

    // Tools Blocks
    "TOOLS_COMMENT": "註解 %1",

    // Visual Blocks
    "VISUAL_STAGE_SETUP_TITLE": "建立表演舞台",
    "VISUAL_STAGE_SETUP_DIMENSIONS": "尺寸： 寬 %1 高 %2",
    "VISUAL_STAGE_SETUP_APPEARANCE": "外觀： 背景 %1   前景 %2",
    "VISUAL_STAGE_SETUP_SETTINGS": "設定： 波形 %1   |   頻譜 %2   |   日誌 %3   |   MIDI %4",
    "VISUAL_STAGE_SET_COLOR": "設定舞台 %1 顏色為 %2",
    "VISUAL_ELLIPSE": "繪製圓形/橢圓 x %1 y %2 寬 %3 高 %4",
    "VISUAL_TRIANGLE": "繪製三角形 x1 %1 y1 %2 x2 %3 y2 %4 x3 %5 y3 %6",
    "VISUAL_ROTATE": "旋轉角度 %1 度",
    "VISUAL_TRANSLATE": "移動座標至 x %1 y %2",
    "VISUAL_PUSH_POP": "隔離座標與樣式變換 %1",
    "VISUAL_SCALE": "縮放畫布 %1 倍",
    "AUDIO_CREATE_SYNTH_INSTRUMENT": "建立合成器樂器 名稱 %1 類型 %2",
    "AUDIO_CREATE_HARMONIC_SYNTH": "設定為諧波合成器",
    "AUDIO_CREATE_ADDITIVE_SYNTH": "設定為加法合成器",
    "SB_INSTRUMENT_CONTAINER_MESSAGE": "定義樂器 名稱 %1 %2",
    "SB_INSTRUMENT_CONTAINER_TOOLTIP": "樂器定義容器。請在內部放置波形、ADSR 等設定積木。",
    "SB_SET_ADSR_MESSAGE": "設定 ADSR",
    "SB_SET_ADSR_TOOLTIP": "設定此樂器的 ADSR 包絡線 (0.0 ~ 1.0+)。",
    "SB_SET_WAVE_MESSAGE": "設定波形",
    "SB_SET_WAVE_TOOLTIP": "設定此樂器的基本波形。",
    "AUDIO_HARMONIC_FIELD": "%1 倍頻 振幅 (0-1)",
    "AUDIO_ADDITIVE_FIELD": "波形 %1 頻率倍率 %2 振幅 %3",
    "AUDIO_SELECT_INSTRUMENT": "選取目前樂器為 %1",
    "AUDIO_SELECT_INSTRUMENT_TOOLTIP": "從目前工作區已定義的樂器清單中，選取一個作為目前演奏的樂器。",
    "HELP_LANG_SUFFIX": "_zh-hant.html",
    "HELP_HINT": "\n按右鍵選擇「說明」了解更多用法。",
    "AUDIO_PLAY_NOTE": "合成器開始發聲 音高 %1 力度 %2",
    "AUDIO_STOP_NOTE": "合成器停止發聲 (MIDI %1)",
    "AUDIO_PLAY_MELODY": "演奏旋律 樂器 %1 %2 內容 %3",
    "AUDIO_PLAY_MELODY_TOOLTIP": "按照清單順序演奏。支援多行、音符 (C4, D4) 與和弦 (CM7, G7)。",
    "AUDIO_RHYTHM_SEQUENCE": "節奏序列 聲源 %1 樣式 %2 第 %3 小節",
    "AUDIO_SET_BPM": "設定演奏速度 (BPM) %1",
    "AUDIO_DEFINE_CHORD": "定義和弦 名稱 %1 音符列表 %2",
    "AUDIO_PLAY_CHORD_BY_NAME": "演奏和弦 %1 時值 %2 力度 %3",
    "MIDI_OFF_NOTE": "當收到 MIDI 音符 OFF %1 %2 頻道 %3 鍵號 %4 力度 %5 %6 %7",
    "UI_KEY_EVENT": "當按下鍵盤 %1 鍵 %2",
    "UI_KEY_EVENT_TOOLTIP": "當偵測到特定按鍵被按下時執行動作。鋼琴音階鍵在舞台啟動時無法自訂。",
    "UI_INIT": "啟動 UI 系統 (ControlP5)",
    "UI_INIT_TOOLTIP": "初始化 ControlP5 介面庫，以便建立滑桿與切換開關。",
    "UI_ADD_SLIDER": "新增滑桿 %1 位置 x %2 y %3 寬 %4 高 %5 %6 範圍 %7 到 %8 初始值 %9 標籤 %10",
    "UI_ADD_TOGGLE": "新增切換開關 名稱 %1 位置 x %2 y %3 初始狀態 %4 標籤 %5",
    "UI_SET_FONT_SIZE": "設定 UI 字體大小 %1",
    "VISUAL_NO_STROKE": "不繪製邊框",
    "VISUAL_NO_FILL": "不填充顏色",
    "VISUAL_PIXEL_DENSITY": "優化高解析度螢幕顯示 (pixelDensity)",
    "VISUAL_PIXEL_DENSITY_TOOLTIP": "在高解析度螢幕（如 Retina）上開啟 2 倍渲染，讓線條更平滑。",
    "VISUAL_STAGE_SETUP_TOOLTIP": "初始化超級表演舞台（包含自動波形與 FFT）。",
    "MIDI_ON_NOTE_TOOLTIP": "當外部 MIDI 裝置按下琴鍵時執行的動作。",
    "MIDI_OFF_NOTE_TOOLTIP": "當外部 MIDI 裝置放開琴鍵時執行的動作。",
    "AUDIO_TONE_LOOP_TOOLTIP": "持續循環執行內部的積木。INTERVAL 支援 1m, 2n, 4n 等符號。",
    "AUDIO_CREATE_HARMONIC_SYNTH_TOOLTIP": "設定此樂器為諧波合成器。",
    "AUDIO_CREATE_ADDITIVE_SYNTH_TOOLTIP": "設定此樂器為加法合成器。",
    "VISUAL_STAGE_BG": "背景",
    "VISUAL_STAGE_WAVE": "波形",

    // Hues
    "STRUCTURE_HUE": "#16A085",
    "LOGIC_HUE": "#b198de",
    "LOOPS_HUE": "#7fcd81",
    "MATH_HUE": "#5C68A6",
    "LISTS_HUE": "#745ca6",
    "TEXT_HUE": "#6a8871",
    "VARIABLES_HUE": "#ef9a9a",
    "FUNCTIONS_HUE": "#d22f73",
    "TOOLS_HUE": "#6a8871",
    "LIVE_SHOW_HUE": "#2C3E50",
    "SOUND_SOURCES_HUE": "#E74C3C",
    "INSTRUMENT_CONTROL_HUE": "#D22F73",
    "PERFORMANCE_HUE": "#E67E22",
    "MIDI_HUE": "#5B67E7",
    "PC_KEY_HUE": "#2c3e50",
    "SERIAL_HUE": "#2c3e50",
    "UI_HUE": "#FFB300",
    "VISUAL_HUE": "#3498DB",

    // Processing Structure Blocks
    "BKY_PROCESSING_SETUP_MSG_ANGEL": "當程式啟動時 (setup)",
    "BKY_PROCESSING_DRAW_MSG_ANGEL": "重複執行 (draw)",
    
    "PROCESSING_SETUP_TOOLTIP": "setup() 在程式開始時執行一次。用於設定視窗大小、初始化樂器與變數。",
    "PROCESSING_DRAW_TOOLTIP": "draw() 會不斷重複執行（預設每秒 60 次）。用於更新視覺動畫與處理即時互動。",

    // Math Property Checks
    "MATH_IS_EVEN": "是偶數",
    "MATH_IS_ODD": "是奇數",
    "MATH_IS_WHOLE": "是整數",
    "MATH_IS_POSITIVE": "是正數",
    "MATH_IS_NEGATIVE": "是負數",
    "MATH_IS_DIVISIBLE_BY": "可被整除",

    // Common
    "VISUAL_EXIT": "結束程式",
    "VISUAL_EXIT_TOOLTIP": "立即關閉表演舞台並結束程式執行。",
    "STRUCTURE_DELAY": "等待 %1 毫秒",
    "STRUCTURE_DELAY_TOOLTIP": "暫停程式執行一段時間。注意：這會讓視覺動畫跟著停頓。",
    "AUDIO_IS_PLAYING": "是否有旋律在播放？",
    "AUDIO_IS_PLAYING_TOOLTIP": "檢查背景旋律播放器是否仍在運作中。",
    "BKY_CONTROLS_DO": "執行",
  });
})(Blockly);