(function (Blockly) {
  Blockly.Msg = Blockly.Msg || {};
  Object.assign(Blockly.Msg, {
    // SynthBlockly Stage - Traditional Chinese
    
    // Toolbar Tooltips
    "BKY_TOOLBAR_SAVE_TOOLTIP": "儲存專案 (XML)",
    "BKY_TOOLBAR_SAVE_AS_TOOLTIP": "另存專案",
    "BKY_TOOLBAR_CLOSE_TOOLTIP": "關閉工作區",
    "BKY_TOOLBAR_NEW_TOOLTIP": "建立新專案",
    "BKY_TOOLBAR_OPEN_TOOLTIP": "開啟專案",

    // Category Keys
    "CAT_STRUCTURE": "程式結構",
    "CAT_LOGIC": "邏輯判斷",
    "CAT_LOOPS": "迴圈控制",
    "CAT_MATH": "數學運算",
    "CAT_TEXT": "文字處理",
    "CAT_LISTS": "列表處理",
    "CAT_VARIABLES": "變數管理",
    "CAT_FUNCTIONS": "自訂函式",
    "CAT_TOOLS": "工具",
    "CAT_LIVE_SHOW": "表演舞台",
    "CAT_SOUND_SOURCES": "建立樂器",
    "CAT_INSTRUMENT_CONTROL": "樂器控制",
    "CAT_PERFORMANCE": "音樂演奏",
    "CAT_MIDI": "MIDI 通訊",
    "CAT_PC_KEY": "電腦鍵盤 (PC Key)",
    "CAT_SERIAL": "序列埠通訊 (Serial)",
    "CAT_EFFECTS": "音訊效果器",
    "CAT_UI": "介面控制 (UI)",
    "CAT_VISUAL": "視覺繪圖",

    // Effect Blocks
    "SB_SETUP_EFFECT_MESSAGE": "設定效果器 類型 %1",
    "SB_EFFECT_FILTER_TYPE_FIELD": "濾波器 (Filter)",
    "SB_EFFECT_DELAY_TYPE_FIELD": "延遲 (Delay)",
    "SB_EFFECT_BITCRUSH_TYPE_FIELD": "位元破壞 (BitCrush)",
    "SB_EFFECT_WAVESHAPER_TYPE_FIELD": "波形塑形 (Waveshaper)",
    "SB_EFFECT_COMPRESSOR_TYPE_FIELD": "壓縮器 (Compressor)",
    "SB_EFFECT_LIMITER_TYPE_FIELD": "限制器 (Limiter)",
    "SB_EFFECT_REVERB_TYPE_FIELD": "混響 (Reverb)",
    "SB_EFFECT_FLANGER_TYPE_FIELD": "飛機音 (Flanger)",
    "SB_EFFECT_AUTOFILTER_TYPE_FIELD": "自動濾波 (Auto-Filter)",
    "SB_EFFECT_PITCHMOD_TYPE_FIELD": "音高調變 (Pitch-Mod)",
    "SB_EFFECT_FILTER_INTERNAL_TYPE_FIELD": "模式",
    "SB_EFFECT_MOD_TYPE_FIELD": "調變類型",
    "SB_EFFECT_MOD_TYPE_JITTER": "抖動 (Jitter)",
    "SB_EFFECT_MOD_TYPE_VIBRATO": "顫音 (Vibrato)",
    "SB_EFFECT_FILTER_FREQ_FIELD": "頻率",
    "SB_EFFECT_FILTER_Q_FIELD": "共振 (Q)",
    "SB_EFFECT_DELAY_TIME_FIELD": "延遲時間 (秒)",
    "SB_EFFECT_FEEDBACK_FIELD": "回饋 (Feedback)",
    "SB_EFFECT_RATE_FIELD": "速率 (Hz)",
    "SB_EFFECT_DEPTH_FIELD": "深度",
    "SB_EFFECT_BITDEPTH_FIELD": "位元深度 (Bits)",
    "SB_EFFECT_DISTORTION_AMOUNT_FIELD": "失真量",
    "SB_EFFECT_ROOMSIZE_FIELD": "房間大小",
    "SB_EFFECT_DAMPING_FIELD": "高頻吸收",
    "SB_EFFECT_WET_FIELD": "濕度 (Wet)",
    "SB_EFFECT_ROLLOFF_FIELD": "衰減",
    "SB_EFFECT_THRESHOLD_FIELD": "門檻 (Threshold dB)",
    "SB_EFFECT_RATIO_FIELD": "比率 (Ratio)",
    "SB_EFFECT_ATTACK_FIELD": "啟動時間 (Attack s)",
    "SB_EFFECT_RELEASE_FIELD": "釋放時間 (Release s)",
    "SB_EFFECT_MAKEUP_FIELD": "增益補償 (Makeup dB)",
    "SB_SETUP_EFFECT_TOOLTIP": "設定並套用音訊效果器。放在樂器容器內可設定該樂器效果；放在外面（如 setup 中）則作用於全域 Master 混音。支援多個效果器串接。",
    "SB_SET_EFFECT_PARAM_TITLE": "更新效果器參數 樂器 %1 類型 %2",
    "SB_SET_EFFECT_PARAM_PARAM": "參數 %1",
    "SB_SET_EFFECT_PARAM_VALUE": "數值",
    "SB_SET_EFFECT_PARAM_PAN_LABEL": "位置 (-1~1)",
    "SB_UPDATE_ADSR_TITLE": "更新 ADSR 樂器 %1",
    "SB_SET_EFFECT_PARAM_TOOLTIP": "即時更新指定樂器的效果器參數。",
    "SB_UPDATE_ADSR_TOOLTIP": "即時更新指定樂器的 ADSR 包絡線設定。",
    "SB_SELECT_INSTRUMENT_PROMPT": "(請選擇樂器)",
    "SB_CURRENT_INSTRUMENT_OPTION": "當前選用的樂器",
    "SB_NO_EFFECTS_AVAILABLE": "(無可用效果器)",
    "SB_NO_INSTRUMENT_SELECTED": "(尚未選取樂器)",
    "SB_ERROR_INSTRUMENT_NOT_FOUND": "找不到指定的樂器容器：%1",
    "SB_ERROR_EFFECT_NOT_FOUND": "該樂器目前的設定中沒有此效果器：%1",

    // Tools Blocks
    "LIVE_SET_PARAM": "設定舞台參數 %1 為 %2",
    "LIVE_GET_PARAM": "舞台參數 %1",
    "SB_LOG_TO_SCREEN": "寫入舞台日誌 %1 類型 %2",
    "SB_LOG_TYPE_INFO": "INFO",
    "SB_LOG_TYPE_MSG": "!",
    "SB_LOG_TYPE_WARN": "WARN",
    "SB_LOG_TYPE_ERR": "ERR",
    "SB_LOG_TO_SCREEN_TOOLTIP": "將訊息輸出到舞台的控制台或警告區域。",
    "LIVE_PARAM_WAVE_SCALE": "波形縮放 (waveScale)",
    "LIVE_PARAM_TRAIL_ALPHA": "殘影透明度 (trailAlpha)",
    "LIVE_PARAM_FG_HUE": "前景顏色 (fgHue)",
    "LIVE_PARAM_MASTER_GAIN": "主音量 (masterGain)",
    "LIVE_PARAM_TRANSPOSE": "移調 (pitchTranspose)",
    "LIVE_PARAM_ADSR_A": "包絡線 A (adsrA)",
    "LIVE_PARAM_ADSR_D": "包絡線 D (adsrD)",
    "LIVE_PARAM_ADSR_S": "包絡線 S (adsrS)",
    "LIVE_PARAM_ADSR_R": "包絡線 R (adsrR)",

    // Serial Blocks
    "SERIAL_INIT": "初始化序列埠 索引 %1 波特率 %2",
    "SERIAL_AVAILABLE": "序列埠有新資料？",
    "SERIAL_READ_STRING": "讀取字串直到換行",
    "SERIAL_WRITE": "寫入序列埠 內容 %1",
    "SERIAL_DATA_RECEIVED": "當收到序列埠資料時 %1 存入變數 %2 %3",
    "SERIAL_CHECK_MASK": "檢查位元遮罩 %1 是否包含鍵碼 %2",
    "SB_SERIAL_CHECK_KEY_MASK_MESSAGE": "檢查資料 %1 中按鍵 %2 是否按下？",
    "SB_SERIAL_CHECK_KEY_MASK_TOOLTIP": "解析位元遮罩資料 (例如 KEYS:5)，檢查特定按鍵是否包含在內。",

    // Tools Blocks
    "TOOLS_COMMENT": "註解 %1",

    // Visual Blocks
    "VISUAL_STAGE_SETUP_TITLE": "建立表演舞台",
    "VISUAL_STAGE_SETUP_DIMENSIONS": "尺寸： 寬 %1 高 %2",
    "VISUAL_STAGE_SETUP_APPEARANCE": "外觀： 背景 %1   前景 %2",
    "VISUAL_STAGE_SETUP_SETTINGS": "設定： 波形 %1   |   頻譜 %2   |   日誌 %3   |   MIDI %4",
    "VISUAL_STAGE_SET_COLOR": "設定舞台 %1 顏色為 %2",
    "VISUAL_ELLIPSE": "繪製圓形/橢圓 x %1 y %2 寬 %3 高 %4",
    "VISUAL_TRIANGLE": "繪製三角形 x1 %1 y1 %2 x2 %3 y2 %4 x3 %5 y3 %6",
    "VISUAL_ROTATE": "旋轉角度 %1 度",
    "VISUAL_TRANSLATE": "移動座標至 x %1 y %2",
    "VISUAL_PUSH_POP": "隔離座標與樣式變換 %1",
    "VISUAL_SCALE": "縮放畫布 %1 倍",
    "AUDIO_CREATE_SYNTH_INSTRUMENT": "建立合成器樂器 名稱 %1 類型 %2",
    "AUDIO_CREATE_HARMONIC_SYNTH": "設定為諧波合成器",
    "AUDIO_CREATE_ADDITIVE_SYNTH": "設定為加法合成器",
    "SB_INSTRUMENT_CONTAINER_MESSAGE": "定義樂器 名稱 %1 %2",
    "SB_INSTRUMENT_CONTAINER_TOOLTIP": "樂器定義容器。請在內部放置波形、ADSR 等設定積木。",
    "SB_INSTRUMENT_CONTAINER_MULTI_SOURCE_WARN": "警告：一個樂器容器內只能有一個音源積木（波形、噪音、混合音源、取樣器、或合成器）。後方的積木將會覆寫前方的類型。",
    "SB_SET_ADSR_MESSAGE": "設定 ADSR",
    "SB_SET_ADSR_TOOLTIP": "設定此樂器的 ADSR 包絡線 (0.0 ~ 1.0+)。",
    "SB_SET_ADSR_SAMPLER_WARN": "提示：旋律取樣器目前僅支援 Release (R) 餘韻設定，A/D/S 將被忽略以維持原音品質。",
    "SB_SET_WAVE_MESSAGE": "設定波形 %1",
    "SB_SET_WAVE_TOOLTIP": "設定此樂器的基本波形。",
    "SB_SET_NOISE_MESSAGE": "設定噪聲 類型 %1",
    "SB_SET_NOISE_TOOLTIP": "設定此樂器為噪聲產生器（常用於製作擊奏音效或背景氛圍）。",
    "SB_MIXED_SOURCE_MESSAGE": "設定混合音源 波形 %1 + 噪音 %2 比例(噪音) %3",
    "SB_MIXED_SOURCE_TOOLTIP": "同時混合基礎波形與隨機噪音，創造具備空氣感或質感的複雜音色。",
    "SB_MIXED_SOURCE_JITTER": "抖動 (Jitter)",
    "SB_MIXED_SOURCE_SWEEP_RATE": "掃頻速率",
    "SB_MIXED_SOURCE_SWEEP_DEPTH": "掃頻深度",
    "SB_SET_PANNING_MESSAGE": "設定樂器相位",
    "SB_SET_PANNING_INST": "樂器",
    "SB_SET_PANNING_VAL": "位置 (-1~1)",
    "SB_SET_PANNING_TOOLTIP": "調整樂器在立體聲場中的位置。-1 為最左，1 為最右，0 為中間。",
    "AUDIO_HARMONIC_FIELD": "%1 倍頻 振幅 (0-1)",
    "AUDIO_ADDITIVE_FIELD": "波形 %1 頻率倍率 %2 振幅 %3",
    "AUDIO_CREATE_MELODIC_SAMPLER": "設定取樣器(旋律) 聲音來源 %1",
    "AUDIO_CREATE_DRUM_SAMPLER": "設定取樣器(打擊) 聲音來源 %1",
    "AUDIO_SAMPLER_CUSTOM": "自訂路徑...",
    "AUDIO_SAMPLER_PATH_FIELD": "路徑",
    "AUDIO_MELODIC_SAMPLER_PIANO": "鋼琴",
    "AUDIO_MELODIC_SAMPLER_VIOLIN_PIZZ": "小提琴 (撥奏)",
    "AUDIO_MELODIC_SAMPLER_VIOLIN_ARCO": "小提琴 (拉奏)",
    "AUDIO_MELODIC_SAMPLER_CUSTOM": "自訂路徑...",
    "AUDIO_MELODIC_SAMPLER_TOOLTIP": "建立一個可變音高的取樣音源。會自動載入指定資料夾內的取樣並進行智慧變調演奏。",
    "AUDIO_DRUM_SAMPLER_TOOLTIP": "載入打擊樂器樣本檔案 (WAV/MP3/AIFF)。",
    "AUDIO_SELECT_INSTRUMENT": "選取目前樂器為 %1",
    "AUDIO_SELECT_INSTRUMENT_TOOLTIP": "從目前工作區已定義的樂器清單中，選取一個作為目前演奏的樂器。",
    "AUDIO_SET_INSTRUMENT_VOLUME": "設定樂器音量",
    "AUDIO_SET_INSTRUMENT_VOLUME_INST": "樂器",
    "AUDIO_SET_INSTRUMENT_VOLUME_VAL": "音量 %",
    "AUDIO_SET_INSTRUMENT_VOLUME_TOOLTIP": "調整指定樂器的音量比例 (0-100)。",
    "AUDIO_SELECT_INSTRUMENT_DROPDOWN": "(選取樂器)",
    "AUDIO_SELECT_CHORD_DROPDOWN": "(選取和弦)",
    "AUDIO_TRIGGER_SAMPLE": "演奏單音",
    "AUDIO_TRIGGER_SAMPLE_INST": "樂器",
    "AUDIO_TRIGGER_SAMPLE_NOTE": "音符",
    "AUDIO_TRIGGER_SAMPLE_VEL": "力度",
    "AUDIO_TRIGGER_SAMPLE_TOOLTIP": "演奏單一音符或擊奏。範例：'C4' (預設四分), 'X' (擊奏), 'C4H' (二分音符)。時值後綴：W(全), H(二分), Q(四分), E(八分), S(十六分)。",
    "HELP_LANG_SUFFIX": "_zh-hant.html",
    "HELP_HINT": "\n按右鍵選擇「說明」了解更多用法。",
    "AUDIO_PLAY_NOTE": "演奏持續音高",
    "AUDIO_PLAY_NOTE_INST": "樂器",
    "AUDIO_PLAY_NOTE_PITCH": "音高",
    "AUDIO_PLAY_NOTE_VEL": "力度",
    "AUDIO_STOP_NOTE": "停止演奏音高",
    "AUDIO_STOP_NOTE_INST": "樂器",
    "AUDIO_STOP_NOTE_PITCH": "音高",
    "AUDIO_PLAY_NOTE_TOOLTIP": "讓指定樂器開始播放一個持續音。音高支援 MIDI 編號 (如 60) 或音名 (如 'C4')。通常配合鍵盤或 MIDI 按下事件使用。",
    "AUDIO_STOP_NOTE_TOOLTIP": "讓指定樂器停止播放特定音高。音高支援 MIDI 編號 (如 60) 或音名 (如 'C4')。通常配合鍵盤或 MIDI 放開事件使用。",
    "AUDIO_PLAY_MELODY": "播放旋律",
    "AUDIO_PLAY_MELODY_INST": "使用樂器",
    "AUDIO_PLAY_MELODY_SCORE": "樂譜",
    "AUDIO_PLAY_MELODY_TOOLTIP": "按照清單順序演奏。支援多行、音符 (C4, D4) 與和弦 (CM7, G7)。",
    "AUDIO_TONE_LOOP": "每隔 %1 無限反覆演奏 %2",
    "AUDIO_RHYTHM_SEQUENCE": "步進音序器",
    "AUDIO_RHYTHM_SEQUENCE_INST": "樂器",
    "AUDIO_RHYTHM_SEQUENCE_MODE": "模式",
    "AUDIO_RHYTHM_SEQUENCE_MEASURE": "第 %1 小節",
    "AUDIO_RHYTHM_SEQUENCE_PATTERN": "節奏",
    "AUDIO_RHYTHM_SEQUENCE_VELOCITY": "力度",
    "AUDIO_RHYTHM_V2_HEADER": "配置樂句 第 %1 小節 | 拍號 %2/%3 | 每拍切 %4 步",
    "AUDIO_RHYTHM_V2_TRACK": "樂器 %1 力度 %2 模式 %3 節奏 %4",
    "AUDIO_RHYTHM_MODE_MONO": "單音/打擊",
    "AUDIO_RHYTHM_MODE_CHORD": "和弦",
    "AUDIO_RHYTHM_SEQUENCE_TOOLTIP": "在指定小節演奏 16 格節奏。單音模式支援 x(觸發) 或 C4(音高)；和弦模式支援 Dm7 等自訂和弦名稱。",
    "AUDIO_COUNT_IN": "演奏預備拍 %1 小節 拍號 %2 / %3 力度 %4",
    "AUDIO_SET_BPM": "設定演奏速度 (BPM) %1",
    "AUDIO_DEFINE_CHORD": "定義和弦 名稱 %1 音符列表 %2",
    "AUDIO_PLAY_CHORD_BY_NAME": "播放和弦",
    "AUDIO_PLAY_CHORD_BY_NAME_INST": "使用樂器",
    "AUDIO_PLAY_CHORD_BY_NAME_DUR": "時值",
    "AUDIO_PLAY_CHORD_BY_NAME_VEL": "力度",
    "SB_PLAY_DRUM_MESSAGE": "演奏電子鼓 %1 力度 %2",
    "SB_PLAY_DRUM_TOOLTIP": "播放電子鼓取樣音效 (Kick/Snare/HiHat/Clap)。",
    "MIDI_ON_NOTE": "當收到 %1 MIDI 音符 ON %2 頻道 %3 鍵號 %4 力度 %5 %6 %7",
    "MIDI_OFF_NOTE": "當收到 %1 MIDI 音符 OFF %2 頻道 %3 鍵號 %4 力度 %5 %6 %7",
    "MIDI_ON_CONTROLLER_CHANGE": "當收到 %1 MIDI CC 訊號 %2 頻道 %3 號碼 %4 數值 %5 %6 %7",
    "MIDI_ON_CONTROLLER_CHANGE_TOOLTIP": "監聽 MIDI 控制器變更 (Control Change, CC)。",
    "MIDI_INIT": "啟動 MIDI %1 輸入 %2 輸出 %3",
    "MIDI_INIT_TOOLTIP": "初始化 MidiBus 函式庫。輸入/輸出索引可從控制台列表查詢。",
    "MIDI_SEND_NOTE": "傳送 MIDI 音符 %1 頻道 %2 鍵號 %3 力度 %4",
    "MIDI_SEND_NOTE_TOOLTIP": "向 MIDI 輸出裝置傳送 Note On 或 Note Off 訊號。",
    "MIDI_SEND_CC": "傳送 MIDI CC 頻道 %1 號碼 %2 數值 %3",
    "MIDI_SEND_CC_TOOLTIP": "向 MIDI 輸出裝置傳送控制器變更 (CC) 訊號。",
    "MIDI_TYPE_ON": "開啟 (ON)",
    "MIDI_TYPE_OFF": "關閉 (OFF)",
    "MIDI_LP_XY_TO_NOTE": "Launchpad 座標轉鍵號 x %1 y %2",
    "MIDI_LP_XY_TO_NOTE_TOOLTIP": "將 Launchpad S 的 X-Y 座標 (0-7) 轉換為對應的 MIDI 鍵號。座標 (0,0) 為左上角。",
    "UI_KEY_EVENT": "當鍵盤 %1 鍵被 %2",
    "UI_KEY_PRESSED": "按下",
    "UI_KEY_RELEASED": "放開",
    "UI_KEY_EVENT_TOOLTIP": "當偵測到特定按鍵被按下或放開時執行動作。鋼琴音階鍵在舞台啟動時無法自訂。",
    "UI_INIT": "啟動 UI 系統 (ControlP5)",
    "UI_INIT_TOOLTIP": "初始化 ControlP5 介面庫，以便建立滑桿與切換開關。",
    "UI_ADD_SLIDER": "新增滑桿 %1 位置 x %2 y %3 寬 %4 高 %5 %6 範圍 %7 到 %8 初始值 %9 標籤 %10",
    "UI_ADD_TOGGLE": "新增切換開關 名稱 %1 位置 x %2 y %3 初始狀態 %4 標籤 %5",
    "UI_SET_FONT_SIZE": "設定 UI 字體大小 %1",
    "VISUAL_NO_STROKE": "不繪製邊框",
    "VISUAL_NO_FILL": "不填充顏色",
    "VISUAL_PIXEL_DENSITY": "優化高解析度螢幕顯示 (pixelDensity)",
    "VISUAL_PIXEL_DENSITY_TOOLTIP": "在高解析度螢幕（如 Retina）上開啟 2 倍渲染，讓線條更平滑。",
    "VISUAL_FRAME_RATE": "設定每秒幀數 (frameRate) %1",
    "VISUAL_FRAME_RATE_TOOLTIP": "設定 draw() 每秒執行的次數。預設為 60。",
    "VISUAL_STAGE_SETUP_TOOLTIP": "初始化超級表演舞台（包含自動波形與 FFT）。",
    "MIDI_ON_NOTE_TOOLTIP": "當外部 MIDI 裝置按下琴鍵時執行的動作。",
    "MIDI_OFF_NOTE_TOOLTIP": "當外部 MIDI 裝置放開琴鍵時執行的動作。",
    "AUDIO_TONE_LOOP_TOOLTIP": "持續循環執行內部的積木。反覆間隔 支援 1m, 2n, 4n 等符號。",
    "AUDIO_PERFORM_ONCE": "演奏 %1",
    "AUDIO_PERFORM_ONCE_TOOLTIP": "在背景執行緒執行一次內部的演奏積木，適合用於單次表演。多個演奏積木可同時進行多聲部合奏。",
    "AUDIO_CREATE_HARMONIC_SYNTH_TOOLTIP": "設定此樂器為諧波合成器。",
    "AUDIO_CREATE_ADDITIVE_SYNTH_TOOLTIP": "設定此樂器為加法合成器。",
    "VISUAL_STAGE_BG": "背景",
    "VISUAL_STAGE_WAVE": "波形",

    // Hues
    "STRUCTURE_HUE": "#16A085",
    "LOGIC_HUE": "#b198de",
    "LOOPS_HUE": "#7fcd81",
    "MATH_HUE": "#5C68A6",
    "LISTS_HUE": "#745ca6",
    "TEXT_HUE": "#6a8871",
    "VARIABLES_HUE": "#ef9a9a",
    "FUNCTIONS_HUE": "#d22f73",
    "TOOLS_HUE": "#6a8871",
    "LIVE_SHOW_HUE": "#2C3E50",
    "SOUND_SOURCES_HUE": "#AC4B40",
    "INSTRUMENT_CONTROL_HUE": "#FF5722",
    "EFFECTS_HUE": "#8E44AD",
    "PERFORMANCE_HUE": "#E67E22",
    "MIDI_HUE": "#5B67E7",
    "PC_KEY_HUE": "#2c3e50",
    "SERIAL_HUE": "#2c3e50",
    "UI_HUE": "#FFB300",
    "VISUAL_HUE": "#3498DB",

    // Processing Structure Blocks
    "BKY_PROCESSING_SETUP_MSG_ANGEL": "當程式啟動時 (setup)",
    "BKY_PROCESSING_DRAW_MSG_ANGEL": "重複執行 (draw)",
    "STRUCTURE_FRAME_COUNT": "偵測幀數 (frameCount)",
    "STRUCTURE_FRAME_COUNT_TOOLTIP": "取得自程式啟動後經過的畫面總數。",
    
    "PROCESSING_SETUP_TOOLTIP": "setup() 在程式開始時執行一次。用於設定視窗大小、初始化樂器與變數。",
    "PROCESSING_DRAW_TOOLTIP": "draw() 會不斷重複執行（預設每秒 60 次）。用於更新視覺動畫與處理即時互動。",

    // Math Property Checks
    "MATH_IS_EVEN": "是偶數",
    "MATH_IS_ODD": "是奇數",
    "MATH_IS_WHOLE": "是整數",
    "MATH_IS_POSITIVE": "是正數",
    "MATH_IS_NEGATIVE": "是負數",
    "MATH_IS_DIVISIBLE_BY": "可被整除",

    // Common
    "VISUAL_EXIT": "結束程式",
    "VISUAL_EXIT_TOOLTIP": "立即關閉表演舞台並結束程式執行。",
    "SB_WAIT_MUSICAL": "程式等待 %1 %2",
    "SB_WAIT_UNIT_MS": "毫秒 (ms)",
    "SB_WAIT_UNIT_S": "秒 (s)",
    "SB_WAIT_UNIT_BEATS": "拍 (beats)",
    "SB_WAIT_UNIT_MEASURES": "小節 (measures)",
    "SB_WAIT_UNIT_MICROS": "微秒 (µs)",
    "SB_WAIT_MUSICAL_TOOLTIP": "暫停程式執行一段時間。可以選擇以音樂節拍（拍、小節）或標準時間（秒、毫秒）為單位。",
    "SB_MUSICAL_SECTION": "配置樂句 長度 %1 小節 %2 %3",
    "SB_MUSICAL_SECTION_TOOLTIP": "用於配置一段樂句的容器。它會同時啟動內部的所有演奏，並等待指定的小節數結束後才繼續執行下一個積木。這能確保多個音軌同步開始，且樂句銜接精準。",
    "AUDIO_IS_PLAYING": "是否有旋律在播放？",
    "AUDIO_IS_PLAYING_TOOLTIP": "檢查背景旋律播放器是否仍在運作中。",
    "AUDIO_WAIT_UNTIL_FINISHED": "等到所有演奏結束",
    "AUDIO_WAIT_UNTIL_FINISHED_TOOLTIP": "暫停目前執行緒，直到背景所有旋律或循環演奏完畢。",
    "BKY_CONTROLS_DO": "執行",
  });
})(Blockly);